### PR TITLE
Added ability to easier load custom corpuses

### PR DESCRIPTION
**Pull request by bgbg**
To use a different than default corpus, a series of actions need to be
performed (as described
[here](http://www.grantjenks.com/docs/wordsegment/using-a-different-corp
us.html)). This change automates this process without changing the
existing API.

### CODE REVIEW

**Comment by grantjenks** [comment]
Out of curiosity, how often do you use a different corpus? And if I may ask, what other corpus do you use?

**Comment by bgbg** [comment]
Possible scenarios: corpuses based on different potential audience, different languages.

**Comment by grantjenks** [comment]
Superseded by v1.1.3 or greater which is deployed on PyPI.

Do you use wordsegment as part of your work at Automattic? I would love to include a testimonial from you if the package has been useful.

**Comment by bgbg** [comment]
I used this library for an ad-hoc analysis but decided not to adopt another approach.

**Pull request closed without merging**
